### ISSUE TITLE
Could `attributes`  be a `dict`?

### ISSUE THREAD

**Issue by Matt-DESTROYER** [SalladShooter/phyal#11]
Could `attributes` of `Tag`s be a dictionary? Would it make more sense given that you can't have duplicate attributes?

```py
# ...

class Tag:

    def __init__(self, name, text=''):
        self.name = name
        self.attributes = []
        self.children = []
        self.text = text

    def attribute(self, key, value):
        self.attributes.append((key, value))
        return self

# ...
```

**Comment by SalladShooter** [comment]
Hi thanks for the suggestion, and yes! I should probably be able make this change for the next big update planned to release soon (0.3.0).

**Comment by Matt-DESTROYER** [comment]
Would you be open to contributions? Or is this more of a personal project? :)

**Comment by SalladShooter** [comment]
Yes, PHYAL started as a solo project, but in the grand scheme I always wanted community contributions. If you want to work on current source code I can invite you to the source code Repl.

**Comment by SalladShooter** [comment]
> Would you be open to contributions

If you have more ideas, that would be great, especially to keep future updates going.
