### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by aatle** [SalladShooter/PHYAL#12]
A PyPI package or github template should probably have a license.
I'd recommend the *MIT license*.

Info links:
https://choosealicense.com/no-permission/
https://snyk.io/blog/over-10-of-python-packages-on-pypi-are-distributed-without-any-license/  (includes pi chart of PyPI project licenses)

**Comment by SalladShooter** [comment]
Thank you, great idea! I completely forgot about licensing.
