### ISSUE TITLE
Change repository to package repository instead of template

### ISSUE THREAD

**Issue by aatle** [SalladShooter/PHYAL#13]
A PyPI package should have its own dedicated repository. A template would be a separate thing since you would install the package instead of forking its source code.

- [x] Change repository to non-template
- [x] Move source code from `src` to `src/phyal` folder
- [x] Create `pyproject.toml`

**Comment by SalladShooter** [comment]
@SalladShooter how exactly can I do this, what contents would I need in the `pyproject.toml`. Should I remake the Repo to fix it?

**Comment by aatle** [comment]
You do not need to remake the repo.
First, pick a build backend to manage things easier.
Here's some info on python build backends:
https://sinoroc.gitlab.io/kb/python/packaging_tools_comparisons.html#build-back-ends
https://www.reddit.com/r/Python/comments/166a9br/pyprojecttoml_buildbackend_statistics/

You should probably use `poetry` because that is what replit uses. Now, on your local machine use `poetry init` to create a pyproject.toml for an existing project, PHYAL.
Poetry also helps publish your package.

Take a look at my own github pypi package, [pyriak](https://github.com/aatle/pyriak), for reference.

(I recently moved from replit to github + local machine. I am an inactive TL3 in ask replit right now.)

There are still many improvements you can make after this, I will post some issues later.

**Comment by SalladShooter** [comment]
@aatle thank you so much for the resources, looking forward to future ideas.

**Comment by aatle** [comment]
The last two tasks do not seem to be fixed yet. This issue should be reopened.
