### ISSUE TITLE
Remove unnecessary files, add `.gitignore`

### ISSUE THREAD

**Issue by aatle** [SalladShooter/phyal#15]
There are leftover files from the replit import, and also unnecessary python cache files.
I am not sure about the `static` folder, can it be removed?

To maintain the repo's neatness, add a `.gitignore` file to ignore files such as text editor or python caches. Github's default python gitignore template should suffice.

**Comment by SalladShooter** [comment]
> There are leftover files from the replit import, and also unnecessary python cache files. I am not sure about the `static` folder, can it be removed?

I made it mostly for testing to easily access CSS and JS files, but it could be removed for the main 0.3.0 update, or kept to keep it convenient.

**Comment by aatle** [comment]
> I made it mostly for testing to easily access CSS and JS files, but it could be removed for the main 0.3.0 update, or kept to keep it convenient.

In general, I would think that testing either goes in a `tests` folder, or you could test on a separate repo/program. I currently use replit to semi-automatically install and test pyriak before releases.

**Comment by aatle** [comment]
Also, a few notes.
It is best to create a new branch to work on an issue or feature, and then create a pull request that references this issue. That way, everyone can see changes, and possibly comment on and refine them before merging.
The first part of this issue, unnecessary files, has not been resolved yet. Fix this or reopen the issue.
